---
title: District HIV Estimates
output: html_document
date: '`r format(Sys.Date(), "%B %d, %Y")`'
fig_width: 5
fig_height: 5
params:
  output_zip: NA
---
  
```{r read_outputs, echo=FALSE, message = FALSE, warning = FALSE}
  
# Read in files from naomi outputs zip
output_zip <- params$output_zip

outputs <- naomi::read_output_package(output_zip)
inputs <- unz(output_zip, "info/inputs.csv") 
inputs <- read.csv(inputs)
options <- unz(output_zip, "info/options.yml")
options <- yaml::read_yaml(options)


indicators <- naomi::add_output_labels(outputs) %>%
dplyr::left_join(outputs$meta_area %>% dplyr::select(area_level, area_id, center_x, center_y)) %>%
sf::st_as_sf()

# Grab inputs and model options from model output zip file
# # concatenating strings where more than one option may be selected

quarter <- options$calendar_quarter_t2
iso <- options$area_scope
period <- outputs$meta_period[outputs$meta_period$calendar_quarter == quarter,]$quarter_label
country <- paste0(outputs$meta_area[outputs$meta_area$area_id == iso,]$area_name, sep = "", collapse = "")
level <- as.integer(options$area_level)
survey_prev = paste0(options$survey_prevalence, sep = " ", collapse = "")
survey_art = paste0(options$survey_art_coverage, sep = " ", collapse = "")
survey_recent = paste0(options$survey_recently_infected, sep = " ", collapse = "")
spectrum_file = paste0(inputs[inputs$role == "pjnz",]$filename)


# Filter data for area + calendar options selected in model run 
data <- dplyr::filter(indicators, 
area_level == level, 
calendar_quarter == quarter)

## Legend functions

## Map Figure
map_outputs <- function(geom_data,
                        var,
                        age, 
                        sex,
                        start_colour_scale, 
                        end_colour_scale, 
                        legend_title, 
                        legend_label = ggplot2::waiver(), 
                        fig_title) {
  # filter data for desired indicator
  fig_data <- geom_data %>% dplyr::filter(indicator == var, 
                                          age_group == age,
                                          sex == sex)
  # generate figure
  ggplot2::ggplot(fig_data, ggplot2::aes(fill = mean)) +
    ggplot2::geom_sf() +
    ggplot2::coord_sf(datum = NA) +
    ggplot2::scale_fill_gradient(low = start_colour_scale,
                                 high = end_colour_scale,
                                 name = legend_title,
                                 guide = "legend", 
                                 labels = legend_label
    )+
    ggplot2::theme_bw() +
    ggplot2::theme(legend.position = "bottom",
                   legend.direction = "vertical", 
                   plot.title = ggplot2::element_text(size = 8, face = "bold"), 
                   legend.text = ggplot2::element_text(size = 8), 
                   legend.title = ggplot2::element_text(size = 8, face = "bold", hjust = 0.5),
                   legend.key.size = ggplot2::unit(0.7, "lines"),
                   legend.background = ggplot2::element_rect(linetype = "dashed", colour = "black"),
                   legend.title.align = 0.5, 
                   plot.margin = ggplot2::margin(0, 0.4, 0, 0.4, "cm")) +
    ggplot2::ggtitle(fig_title)
  
  
}

## Pop pyramid
pop_pyramid_outputs <- function(disag_data,
                                var,
                                left_colour, 
                                right_colour, 
                                x_axis_title, 
                                legend_label = abs, 
                                fig_title) {
  # filter data for desired indicator
  fig_data <- disag_data %>% dplyr::filter(indicator == var) 
  plot <- ggplot2::ggplot(fig_data, ggplot2::aes(x = ifelse(sex == "male", -mean, mean),
                                                 y = age_group,
                                                 ymin = lower,
                                                 ymax = upper,
                                                 fill = sex)) +
    ggplot2::geom_col(width = 0.85) +
    ggplot2::scale_x_continuous(labels = legend_label,
                                limits = max(fig_data$mean) * c(-1,1)) +
    ggplot2::labs(x = x_axis_title) +
    ggplot2::scale_fill_manual(values = c("male" = left_colour, "female" = right_colour)) +
    ggplot2::theme_classic(base_size = 10) +
    ggplot2::theme(legend.position = "top", 
                   plot.title = ggplot2::element_text(size = 8, face = "bold",
                                             hjust = 0.5),
                   axis.title = ggplot2::element_text(size = 6), 
                   axis.text.x = ggplot2::element_text(size = 5),
                   axis.text.y = ggplot2::element_text(size = 5),
                   legend.title = ggplot2::element_blank(),
                   legend.text = ggplot2::element_text(size = 6), 
                   legend.key.size = ggplot2::unit(0.5, "lines"),
                   plot.margin = ggplot2::margin(0.5, 0.3, 0.5, 0.3, "cm")) +
    ggplot2::ylab("Age Group") +
    ggplot2::ggtitle(fig_title)
  
}


```

<style type="text/css">
.main-container {
max-width: 1800px;
margin-left: 10;
margin-right: 10;
}
</style>


``` {r, echo = FALSE, results = 'asis'}
cat(paste0("#### These  are **", country, "** estimates for **", period, "**."), sep = "\n")
```


Naomi combines district-level data about HIV from several sources in a statistical model:

```{r, echo = FALSE, results = 'asis'}
text <- tibble::tibble(prefix = c("National Spectrum data from file: ",
                                  "National household survey data on HIV prevalence: ", 
                                  "National household survey data on ART coverage: ", 
                                  "National household survey data on new HIV infections: "), 
                       source = c(spectrum_file, survey_prev, survey_art, survey_recent))
text$source <- ifelse(text$source == " ",
                      "not specified",
                      text$source)
cat(paste0("* ", text$prefix, "**", text$source, "**"), sep = "\n")
```

### **Geographical distribution of PLHIV**

```{r, echo=FALSE,warning = FALSE, out.width  =  "75%", results = 'asis' }

#-------------------------------------------------------------------------------
# Map: PLHIV (mean)
# # By lowest area_level
#-------------------------------------------------------------------------------
p1 <- map_outputs(geom_data = data, 
                  var = "plhiv",
                  age = "15-49", 
                  sex = "both", 
                  start_colour_scale = "white", 
                  end_colour_scale = "red4", 
                  fig_title = "People living with HIV (15-49)",
                  legend_title = "PLHIV")


#-------------------------------------------------------------------------------
# Map: on ART
# # By lowest area_level
#-------------------------------------------------------------------------------
p2 <- map_outputs(geom_data = data, 
                  var = "art_num_residents",
                  age = "15+", 
                  sex = "both", 
                  start_colour_scale = "white", 
                  end_colour_scale = "olivedrab4", 
                  fig_title = "Residents receiving ART (15+)",
                  legend_title = "Number on ART"
)

#-------------------------------------------------------------------------------
# Map: new infections (mean)
# # By lowest area_level
#-------------------------------------------------------------------------------
p3 <- map_outputs(geom_data = data, 
                  var = "infections",
                  age = "15-49", 
                  sex = "both", 
                  start_colour_scale = "white", 
                  end_colour_scale = "skyblue4", 
                  fig_title = "Annual HIV infections (15-49)",
                  legend_title = "Infections" )


grid::grid.draw(cbind(ggplot2::ggplotGrob(p1), ggplot2::ggplotGrob(p2), 
                      ggplot2::ggplotGrob(p3)))

```

### **Geographical distribution of rates of HIV infection**

```{r, echo=FALSE,warning = FALSE, out.width  =  "75%", results = 'asis' }

#-------------------------------------------------------------------------------
# Map: PLHIV (mean)
# # By lowest area_level
#-------------------------------------------------------------------------------
p4 <- map_outputs(geom_data = data, 
                  var = "prevalence",
                  age = "15-49", 
                  sex = "both", 
                  start_colour_scale = "white", 
                  end_colour_scale = "red4", 
                  fig_title = "HIV prevalence (15-49)",
                  legend_title = "Prevalence", 
                  legend_label = scales::percent_format())

#-------------------------------------------------------------------------------
# Map: new infections (mean)
# # By lowest area_level
#-------------------------------------------------------------------------------
p5 <- map_outputs(geom_data = data, 
                  var = "art_coverage",
                  age = "15+", 
                  sex = "both", 
                  start_colour_scale = "white", 
                  end_colour_scale = "olivedrab4", 
                  fig_title = "Proportion PLHIV on ART (15+)",
                  legend_title = "ART Coverage", 
                  legend_label = scales::percent_format()
)

#-------------------------------------------------------------------------------
# Map: on ART
# # By lowest area_level
#-------------------------------------------------------------------------------
p6 <- map_outputs(geom_data = data, 
                  var = "incidence",
                  age = "15-49", 
                  sex = "both", 
                  start_colour_scale = "white", 
                  end_colour_scale = "skyblue4", 
                  fig_title = "Rate of HIV infection (15-49)",
                  legend_title = "Incidence per 1000", 
                  legend_label = scales::label_number(0.01, 1000)
)

grid::grid.draw(cbind(ggplot2::ggplotGrob(p4), ggplot2::ggplotGrob(p5), 
                      ggplot2::ggplotGrob(p6)))

```

### **Distribution of HIV by age and sex**

```{r, echo = FALSE, warning = FALSE, message= FALSE, out.width = "75%", fig.height = 3, fig.width = 6}

area_levels <- levels(as.factor(indicators$area_level))

if("0" %in% area_levels){
  area_filter = 0
} else {
  area_filter = min(indicators$area_level)
} 

age_sex <- indicators %>% sf::st_drop_geometry()%>%
  dplyr::left_join(outputs$meta_age_group) %>%
  dplyr::filter(area_level == area_filter,
                calendar_quarter == quarter,
                sex != "both",
                age_group %in% get_five_year_age_groups()) %>%
  dplyr::left_join(naomi::get_age_groups()) %>%
  dplyr::mutate(age_group = forcats::fct_reorder(age_group_label, age_group_sort_order),
                sex = factor(sex, levels = c("male", "female")) )


#-------------------------------------------------------------------------------
# Pop Pyramid: PLHIV (mean)
# # By age and sex (15-49)
#-------------------------------------------------------------------------------
p7 <- pop_pyramid_outputs(disag_data = age_sex,
                          var = "plhiv",
                          left_colour = "mistyrose2",
                          right_colour = "red4",
                          x_axis_title = "PLHIV",
                          fig_title = "People living with HIV"
)

#-------------------------------------------------------------------------------
# Pop Pyramid: On ART (mean)
# # By age and sex (15-49)
#-------------------------------------------------------------------------------
p8 <- pop_pyramid_outputs(disag_data = age_sex,
                          var = "art_num_residents",
                          left_colour = "honeydew3",
                          right_colour = "olivedrab4",
                          x_axis_title = "Number on ART",
                          fig_title = "Residents receiving ART"
)


p8 <- p8 + ggplot2::theme(
  axis.title.y = ggplot2::element_blank(),
  axis.text.y = ggplot2::element_blank(),
  axis.ticks.y = ggplot2::element_blank()
)

#-------------------------------------------------------------------------------
# Pop Pyramid: New Infections
# # By age and sex (15-49)
#-------------------------------------------------------------------------------
p9 <- pop_pyramid_outputs(disag_data = age_sex,
                          var = "infections",
                          left_colour = "slategray3",
                          right_colour = "skyblue4",
                          x_axis_title = "Infections",
                          fig_title = "Annual HIV infections"
)

p9 <- p9 + ggplot2::theme(
  axis.title.y = ggplot2::element_blank(),
  axis.text.y = ggplot2::element_blank(),
  axis.ticks.y = ggplot2::element_blank()
)

# Plot figs together
grid::grid.draw(cbind(ggplot2::ggplotGrob(p7), ggplot2::ggplotGrob(p8), 
                      ggplot2::ggplotGrob(p9)))

```




### **District level HIV trends**


``` {r, echo=FALSE, warning = FALSE, result = "asis", fig.height = 8, fig.width = 12, align = 'centre'}
# Check output data for area levels avalible
## If national level data is present, generate figure comparing district level 
## indicator to national level otherwise generate district level figure


if("0" %in% area_levels) {
  
  # Define National level indicators
  
  national <- indicators %>% 
    sf::st_drop_geometry() %>%
    dplyr::filter(area_level == 0,
                  sex == "both",
                  age_group_label == "15-49",
                  calendar_quarter == quarter)
  
  national_inc <- national[national$indicator == "incidence",]$mean
  national_prev <- national[national$indicator == "prevalence",]$mean
  national_art <- national[national$indicator == "art_coverage",]$mean
  
  #-----------------------------------------------------------------------------
  # Barplot: Preavalence
  # # By lowest area_level, descending, compared to national indicator
  #-----------------------------------------------------------------------------
  p13 <- data %>% sf::st_drop_geometry() %>%
    dplyr::filter(indicator == "prevalence", 
                  age_group == "15-49",
                  sex == "both", 
    )%>%
    dplyr::mutate(threshold = ifelse(mean > national_prev,"above", "below"),
                  threshold = as.factor(threshold)) %>%
    ggplot2::ggplot(ggplot2::aes(reorder(area_name, mean),
                                 mean,
                                 ymin = lower,
                                 ymax = upper,
                                 fill = threshold)) +
    ggplot2::theme_classic() +
    ggplot2::geom_col(position = "dodge") +
    ggplot2::geom_linerange(position = ggplot2::position_dodge(0.8)) +
    ggplot2::scale_y_continuous(labels = scales::percent_format(1)) +
    ggplot2::theme(
      axis.text.x = ggplot2::element_text(size = 8),
      legend.background = ggplot2::element_rect(linetype = "dashed", colour = "black"),
      legend.text = ggplot2::element_text(size = 8), 
      legend.position = "bottom",
      legend.direction = "vertical", 
      legend.title = ggplot2::element_text(size = 8, face = "bold"), 
      axis.title.x = ggplot2::element_text(size = 8, face = "bold"), 
      axis.title.y = ggplot2::element_blank()) +
    ggplot2::ylab("Prevalence") +
    ggplot2::geom_hline(yintercept= national_prev, linetype="dashed", color = "black")+
    ggplot2::scale_fill_manual(name = paste0("National HIV Prevalence: \n ", round(national_prev*100, 2),"%"),
                               values = c("above" = "red4", "below" = "mistyrose2")) +
    ggplot2::ggtitle("HIV Prevalence") + 
    ggplot2::coord_flip()
  
  
  #-------------------------------------------------------------------------------
  # Barplot: ART coverage
  # # By lowest area_level, descending, compared to national indicator
  #--------------------------------------------------------------------------------
  
  art_colours_2 <- c(">80%" = "olivedrab4", 
                     "70-80%" = "#688C2192", 
                     "<70%" = "#688C2133")
  
  ## assign ART coverage categories 
  art_data <- data %>% 
    dplyr::filter(indicator == "art_coverage", 
                  age_group == "15+",
                  sex == "both") %>%
    dplyr::mutate(mean = round(mean, 2), 
                  threshold = dplyr::case_when(mean >= 0.8 ~ ">80%", 
                                               dplyr::between(mean, 0.7,0.8) ~ "70-80%", 
                                               mean < 0.7 ~ "<70%"), 
                  threshold = factor(threshold, levels = c(">80%", "70-80%", "<70%")))
  
  p14 <- art_data %>% sf::st_drop_geometry() %>%
    dplyr::filter(indicator == "art_coverage") %>%
    ggplot2::ggplot(ggplot2::aes(reorder(area_name, mean),
                                 mean,
                                 ymin = lower,
                                 ymax = upper,
                                 fill = threshold)) +
    ggplot2::theme_classic() +
    ggplot2::geom_col(position = "dodge") +
    ggplot2::geom_linerange(position = ggplot2::position_dodge(0.8)) +
    ggplot2::scale_y_continuous(labels = scales::percent_format(1)) +
    ggplot2::theme(axis.text.x = ggplot2::element_text(size = 8),
                   legend.background = ggplot2::element_rect(linetype = "dashed", colour = "black"),
                   legend.text = ggplot2::element_text(size = 8), 
                   legend.position = "bottom",
                   legend.direction = "vertical", 
                   legend.title = ggplot2::element_text(size = 8, , face = "bold"), 
                   axis.title.x = ggplot2::element_text(size = 8, face = "bold"), 
                   axis.title.y = ggplot2::element_blank()) +
    ggplot2::ylab("ART Coverage") +
    ggplot2::geom_hline(yintercept= national_art, linetype="dashed", color = "black")+
    ggplot2::scale_fill_manual(name = paste0("National ART Coverage:\n ", round(national_art*100, 2),"%"),
                               values = art_colours_2) +
    ggplot2::ggtitle("Proportion PLHIV on ART") +
    ggplot2::coord_flip()
  
  
  #-----------------------------------------------------------------------------
  # Barplot: Incidence per 1000
  # # By lowest area_level, descending, compared to national indicator
  #-----------------------------------------------------------------------------
  p15 <- data %>% dplyr::filter(indicator == "incidence", 
                                age_group == "15-49",
                                sex == "both") %>%
    dplyr::mutate(threshold = ifelse(mean > national_inc,"above", "below"),
                  threshold = as.factor(threshold)) %>%
    ggplot2::ggplot(ggplot2::aes(reorder(area_name, mean),
                                 mean,
                                 ymin = lower,
                                 ymax = upper,
                                 fill = threshold)) +
    ggplot2::theme_classic() +
    ggplot2::geom_col(position = "dodge") +
    ggplot2::geom_linerange(position = ggplot2::position_dodge(0.8)) +
    ggplot2::scale_y_continuous(labels = scales::label_number(0.01, 1000)) +
    ggplot2::theme(axis.text.x = ggplot2::element_text(size = 8),
                   legend.background = ggplot2::element_rect(linetype = "dashed", colour = "black"),
                   legend.text = ggplot2::element_text(size = 8), 
                   legend.position = "bottom",
                   legend.direction = "vertical", 
                   legend.title = ggplot2::element_text(size = 8, face = "bold"), 
                   axis.title.x = ggplot2::element_text(size = 8, face = "bold"), 
                   axis.title.y = ggplot2::element_blank()) +
    ggplot2::ylab("HIV Incidence (per 1000 population)") +
    ggplot2::geom_hline(yintercept= national_inc, linetype="dashed", 
                        color = "black") +
    ggplot2::scale_fill_manual(name = paste0("National HIV Incidence\n per 1000 population: ", round(national_inc*1000, 2)),
                               values = c("above" = "skyblue4", "below" = "slategray3")) +
    ggplot2::ggtitle("Rate of HIV infection") +
    ggplot2::coord_flip()
  
  # Plot figs together 
  grid::grid.draw(cbind(ggplot2::ggplotGrob(p13), ggplot2::ggplotGrob(p14), 
                        ggplot2::ggplotGrob(p15)))
  
} else {
  
  #-----------------------------------------------------------------------------
  # Barplot: Preavalence
  # # By lowest area_level, descending, compared to national indicator
  #-----------------------------------------------------------------------------
  p13 <- data %>% sf::st_drop_geometry() %>%
    dplyr::filter(indicator == "prevalence", 
                  age_group == "15-49",
                  sex == "both", 
    )%>%
    ggplot2::ggplot(ggplot2::aes(reorder(area_name, mean),
                                 mean,
                                 ymin = lower,
                                 ymax = upper)) +
    ggplot2::theme_classic() +
    ggplot2::geom_col(position = "dodge", fill = "red4") +
    ggplot2::geom_linerange(position = ggplot2::position_dodge(0.8)) +
    ggplot2::scale_y_continuous(labels = scales::percent_format(1)) +
    ggplot2::theme(
      axis.text.x = ggplot2::element_text(size = 8),
      axis.title.x = ggplot2::element_text(size = 8, face = "bold"), 
      axis.title.y = ggplot2::element_blank()) +
    ggplot2::ylab("Prevalence") +
    ggplot2::ggtitle("HIV Prevalence") + 
    ggplot2::coord_flip()
  
  #-----------------------------------------------------------------------------
  # Barplot: ART coverage
  # # By lowest area_level, descending, compared to national indicator
  #-----------------------------------------------------------------------------
  
  p14 <- data %>% sf::st_drop_geometry() %>%
    dplyr::filter(indicator == "art_coverage") %>%
    ggplot2::ggplot(ggplot2::aes(reorder(area_name, mean),
                                 mean,
                                 ymin = lower,
                                 ymax = upper)) +
    ggplot2::theme_classic() +
    ggplot2::geom_col(position = "dodge", fill = "olivedrab4") +
    ggplot2::geom_linerange(position = ggplot2::position_dodge(0.8)) +
    ggplot2::scale_y_continuous(labels = scales::percent_format(1)) +
    ggplot2::theme(axis.text.x = ggplot2::element_text(size = 8),, 
                   axis.title.x = ggplot2::element_text(size = 8, face = "bold"), 
                   axis.title.y = ggplot2::element_blank()) +
    ggplot2::ylab("ART Coverage") +
    ggplot2::ggtitle("Proportion PLHIV on ART") +
    ggplot2::coord_flip()
  
  #-----------------------------------------------------------------------------
  # Barplot: Incidence per 1000
  # # By lowest area_level, descending, compared to national indicator
  #-----------------------------------------------------------------------------
  p15 <- data %>% dplyr::filter(indicator == "incidence", 
                                age_group == "15-49",
                                sex == "both") %>%
    ggplot2::ggplot(ggplot2::aes(reorder(area_name, mean),
                                 mean,
                                 ymin = lower,
                                 ymax = upper)) +
    ggplot2::theme_classic() +
    ggplot2::geom_col(position = "dodge", fill = "skyblue4" ) +
    ggplot2::geom_linerange(position = ggplot2::position_dodge(0.8)) +
    ggplot2::scale_y_continuous(labels = scales::label_number(0.01, 1000)) +
    ggplot2::theme(axis.text.x = ggplot2::element_text(size = 8),
                   axis.title.x = ggplot2::element_text(size = 8, face = "bold"), 
                   axis.title.y = ggplot2::element_blank()) +
    ggplot2::ylab("HIV Incidence (per 1000 population)") +
    ggplot2::ggtitle("Rate of HIV infection") +
    ggplot2::coord_flip()
  
  # Plot figs together 
  grid::grid.draw(cbind(ggplot2::ggplotGrob(p13), ggplot2::ggplotGrob(p14), 
                        ggplot2::ggplotGrob(p15)))
  
}


```


### **District Level Indicators**

``` {r, echo = FALSE, warning = FALSE, results = 'asis'}


# # Format data for table
percent_indicators <- c("prevalence", "art_coverage")
whole_indicators <- c("plhiv", "infections", "art_num_attend", "art_num_residents")

x1 <- data %>% sf::st_drop_geometry() %>%
  dplyr::filter(age_group == "15-49",
                sex == "both") %>%
  dplyr::select(area_name, mean, lower, upper, indicator)

# Format indicators
x2 <- x1 %>% dplyr::mutate_if(~is.numeric(.),
                              ~dplyr::if_else(indicator %in% percent_indicators,
                                              round(. *100, 2),
                                              dplyr::if_else(indicator == "incidence", 
                                                      round(.*1000, 2), 
                                                      ceiling(.))))

x3 <- x2  %>% dplyr::mutate(val = ifelse(indicator %in% percent_indicators,
                                         paste0(mean,"%"," (",lower,"-",upper,"%)"),
                                         paste0(mean," (",lower,"-",upper,")")),)
# Melt data in table 
x4 <- x3 %>% 
  dplyr::select(area_name, val, indicator) %>%
  tidyr::spread(indicator, val) %>%
  dplyr::select(area_name, plhiv, prevalence, infections, incidence,
                art_coverage, art_num_residents,
                art_num_attend)


# #-------------------------------------------------------------------------------
# # Table: ART
# # # By lowest area_level, indicators defined above
# #------------------------------------------------------------------------------

x4 %>% gt::gt(rowname_col = "area_name") %>%
  gt::tab_stubhead(label = gt::md("**Area**")) %>%
  gt::tab_options(
    table.align = "left",
    heading.align = "centre",
    column_labels.font.size = "small",
    column_labels.background.color = "grey",
    table.font.size = "smaller",
    data_row.padding = gt::px(3),
  ) %>%
  gt::tab_spanner(
    label = gt::md("**Distribution of HIV**"),
    columns = gt::vars('plhiv', 'prevalence')) %>%
  gt::tab_spanner(
    label = gt::md("**Annual HIV infections**"),
    columns = gt::vars('incidence', 'infections')) %>%
  gt::tab_spanner(
    label = gt::md("**Antiretroviral Treatment**"),
    columns = gt::vars('art_coverage', 'art_num_residents', 'art_num_attend')) %>%
  gt::cols_label(
    plhiv = gt::md("**PLHIV**"),
    prevalence = gt::md("**HIV prevalence**"),
    infections = gt::md("**New infections**"),
    incidence = gt::md("**Incidence (per 1000)**"),
    art_coverage = gt::md("**ART coverage**"),
    art_num_attend = gt::md("**Number residents receiving treatment**"),
    art_num_residents = gt::md("**Number total clients receiving treatment**")
  ) %>%
  gt::cols_align(align = "center") %>%
  gt::cols_width(everything()~ px(150))

```

