
library(tidyverse)
library(here)

devtools::load_all()
data(mwi_area_hierarchy)

#' ## Malawi HIV Programme data
#'
#' Data sources from Integrated Quarterly Reporting spreadsheets available via:
#' https://www.hiv.health.gov.mw/index.php/our-documents
#' 
#' Data are provided by the Ministry of Health, Malawi with the following disclaimer:
#'
#' 1. The data in this file are owned by the Ministry of Health (MOH), Malawi.
#'
#' 2. These data are shared in order to support the National HIV Program.
#'
#' 3. Data in this file may not be used by Third Parties for further analysis and
#'    dissemination without prior written approval of the Director of the Department
#'    for HIV and AIDS, MOH.
#'
#' 4. Patient-level data are routinely collected by health facility staff using
#'    standard monitoring tools. This file contains facility-level aggregates that
#'    have been generated by facility staff and that were verified from primary
#'    records during quarterly National HIV Program Supervision (coordinated of the
#'    Department of HIV and AIDS). While every effort is made to ensure high data
#'    quality, individual records may not be complete and accurate.
#'
#' 5. The official interpretation of these data is presented in Quarterly Integrated
#'    HIV Program Reports and any divergent interpretation may be misleading and is
#'    not supported by the MOH. Analysis and interpretation of the data requires
#'    detailed understsanding of the methods and constraints of the Malawi's National
#'    M&E System.
#'
#' Written approval for inclusion in naomi R package provided by Thoko Kalua via email
#' on 4 September 2019.

mwi_anc_testing <- read_csv(here("data-raw/programme/mwi_dha_ancrt.csv"))

mwi_anc_testing <- mwi_anc_testing %>%
  left_join(
    mwi_area_hierarchy %>% filter(area_level == 4) %>% select(area_name, area_id),
    by = c("district32" = "area_name")
  ) %>%
  mutate(age_group = "15-49") %>%
  group_by(area_id, age_group, year) %>%
  summarise_at(vars(anc_clients, ancrt_known_pos, ancrt_already_art, ancrt_tested, ancrt_test_pos), sum)

mwi_art_number <- read_csv(here("data-raw/programme/mwi_dha_arttot.csv"))

mwi_art_number <- mwi_art_number %>%
  filter(quarter == 4) %>%
  left_join(
    mwi_area_hierarchy %>% filter(area_level == 4) %>% select(area_name, area_id),
    by = c("district32" = "area_name")
  ) %>%
  mutate(district32 = NULL,
         quarter = NULL) %>%
  select(area_id, year, everything())

#' Approximate the number on ART age 15+ as 94% of all
#' Based on Spectrum file outputs, which were triangulated 

mwi_art_number <- mwi_art_number %>%
  mutate(`0-14` = art_tot * 0.06,
         `15+` = art_tot * 0.94,
         art_tot = NULL) %>%
  gather(age_group_label, current_art, `0-14`, `15+`) %>%
  left_join(
    get_age_groups() %>%
    select(age_group_label, age_group)
  ) %>%
  mutate(sex = "both",
         calendar_quarter = paste0("CY", year, "Q4"),
         age_group_label = NULL) %>%
  select(area_id, sex, age_group, year, calendar_quarter, current_art)

usethis::use_data(
           mwi_anc_testing,
           mwi_art_number,
           overwrite = TRUE
         )

dir.create(here("inst/extdata/programme/"))

write_csv(mwi_anc_testing, here("inst/extdata/programme/anc_testing.csv"), na = "")
write_csv(mwi_art_number, here("inst/extdata/programme/art_number.csv"), na = "")
