steps:
  - label: ":whale: Build"
    command: docker/build

  - wait

  - label: ":rstats: Check"
    command: docker/check

  - label: ":hammer: Test"
    command: docker/test
    agents:
      queue: parallel

  - wait

  - label: ":shipit: Push images"
    command: docker/push

  - wait
