#!/usr/bin/env bash
set -e
HERE=$(dirname $0)
. $HERE/common

docker build --pull \
       --build-arg GIT_SHA=$GIT_SHA \
       --build-arg GIT_BRANCH=$GIT_BRANCH \
       --build-arg NAOMI_VERSION=$PACKAGE_VERSION \
       -t $TAG_SHA \
       -f docker/Dockerfile \
       .

# We always push the SHA tagged versions, for debugging if the tests
# after this step fail
docker push $TAG_SHA
