#!/usr/bin/env Rscript

## Runs a model up to the point of preparing the fit and saves it as an RDS
require(naomi)

if (file.exists("tests/testthat/testdata/fit.RDS")) {
  stop("tests/testthat/testdata/fit.RDS exists already - remove file if you want to regenerate")
}

data <- list(
  pjnz = system.file("extdata/demo_mwi2019.PJNZ", package = "naomi"),
  population = system.file("extdata/demo_population_agesex.csv",
    package = "naomi"),
  shape = file.path("tests/testthat/testdata/malawi.geojson"),
  survey = system.file("extdata/survey/survey_hiv_indicators.csv",
    package = "naomi"),
  art = system.file("extdata/demo_art_number.csv", package = "naomi"),
  anc = system.file("extdata/demo_anc_testing.csv", package = "naomi")
)
options <- list(
  area_scope = "MWI",
  area_level = 4,
  t1 = 465,
  t2 = 475,
  survey_prevalence = c("DEMO2016PHIA", "DEMO2015DHS"),
  survey_art_coverage = "DEMO2016PHIA",
  survey_vls = NULL,
  survey_recently_infected = "DEMO2016PHIA",
  survey_art_or_vls = "art_coverage",
  art_t1 = 465,
  art_t2 = 475,
  anc_prevalence_t1 = 464,
  anc_prevalence_t2 = 475,
  anc_art_coverage_t1 = 464,
  anc_art_coverage_t2 = 475
)

message("Preparing inputs")
area_merged <- read_area_merged(data$shape)
population <- read_population(data$population)
survey <- read_survey_indicators(data$survey)
art_number <- read_art_number(data$art)
anc <- read_anc_testing(data$anc)

spec <- extract_pjnz_naomi(data$pjnz)

art_number <- art_number %>%
  dplyr::filter(age_group_id == 20)

## Get from the options
scope <- options$area_scope
level <- options$area_level
quarter_id_t1 <- options$t1
quarter_id_t2 <- options$t2
prev_survey_ids  <- options$survey_prevalence
artcov_survey_ids  <- options$survey_art_coverage
vls_survey_ids <- NULL
recent_survey_ids <- options$survey_recently_infected
art_or_vls <- options$survey_art_or_vls

artnum_quarter_id_t1 <- options$art_t1
artnum_quarter_id_t2 <- options$art_t2

## TODO: make these single values once we have updated to using years instead
## of quarter mrc-577
## TODO: make anc prevalence and anc_art_coverage separate controls of quarter
## in the naomi_model_frame code mrc-645
anc_quarter_id_t1 <- convert_quarter_id(c(4, 1, 2, 3), c(2015, 2016, 2016, 2016))
anc_quarter_id_t2 <- convert_quarter_id(1:4, 2018)
anc_prevalence_t1 <- options$anc_prevalence_t1
anc_prevalence_t2 <- options$anc_prevalence_t2
anc_art_coverage_t1 <- options$anc_art_coverage_t1
anc_art_coverage_t2 <- options$anc_art_coverage_t2

naomi_mf <- naomi_model_frame(area_merged,
                              population,
                              spec,
                              scope = scope,
                              level = level,
                              quarter_id_t1,
                              quarter_id_t2)

naomi_data <- select_naomi_data(naomi_mf,
                                survey,
                                anc,
                                art_number,
                                prev_survey_ids,
                                artcov_survey_ids,
                                recent_survey_ids,
                                vls_survey_ids,
                                artnum_quarter_id_t1,
                                artnum_quarter_id_t2,
                                anc_quarter_id_t1,
                                anc_quarter_id_t2)

tmb_inputs <- prepare_tmb_inputs(naomi_data)

message("Fitting model")
fit <- fit_tmb(tmb_inputs)

message("Generating uncertainty")
fit <- sample_tmb(fit)

message("Saving file")
saveRDS(fit, "tests/testthat/testdata/fit.RDS")
